# Numpy

In [2]:
import numpy as np
print(np.__version__)

1.22.3


## Numpy Array

> Perbedaan paling mendasar adalah array dari numpy = **elementwise**

In [78]:
a = [1, 2, 3, 4, 5]
b = [1, 3, 5, 7, 11]

anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([1, 3, 5, 7, 11])

print(a)
print(b)
print(anp)
print(bnp)
bnp.shape

[1, 2, 3, 4, 5]
[1, 3, 5, 7, 11]
[1 2 3 4 5]
[ 1  3  5  7 11]


(5,)

In [79]:
cnp = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(cnp)
cnp.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

> Array bawaan python **tidak bisa** menggunakan aritmatika

In [41]:
a += [1]
anp += 1
print(a)
print(anp)

[1, 2, 3, 4, 5, 1]
[2 3 4 5 6]


In [67]:
# matrix 0, matrix 1, dan indentitas

zero = np.zeros([2,3])
print(zero)

one = np.ones([3,2])
print("\n", one)

identits = np.identity(3)
identits2 = np.eye(3)
print("\n", identits)
print("\n", identits2)

[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
# np.array dengan range dan linspace

reng = np.arange(1, 6, 1)
linspes = np.linspace(1, 7, 4)

print(reng)
print(linspes)

[1 2 3 4 5]
[1. 3. 5. 7.]


## Aritmatika

In [13]:
a = [1, 2, 3, 4, 5]
b = [1, 3, 5, 7, 11]

anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([1, 3, 5, 7, 11])

print(a)
print(b)
print(anp)
print(bnp)

[1, 2, 3, 4, 5]
[1, 3, 5, 7, 11]
[1 2 3 4 5]
[ 1  3  5  7 11]


In [15]:
c = a + b
print(c)

[1, 2, 3, 4, 5, 1, 3, 5, 7, 11]


In [25]:
print(anp + bnp)
print(anp - bnp)
print(anp * bnp)
print(anp / bnp)
print(anp ** 2)

[ 2  5  8 11 16]
[ 0 -1 -2 -3 -6]
[ 1  6 15 28 55]
[1.         0.66666667 0.6        0.57142857 0.45454545]
[ 1  4  9 16 25]


In [23]:
cnp = np.array(([1,2,3], [4,5,6], [7,8,9]))
dnp = np.array(([4,5,6], [1,2,3], [7,8,9]))

In [24]:
print(cnp + dnp)

[[ 5  7  9]
 [ 5  7  9]
 [14 16 18]]


## Index, Slicing, Iteration

In [30]:
anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([1, 3, 5, 7, 11])

print(f"elemen ke 1 anp = {anp[0]}")
print(f"elemen ke 3 anp = {anp[2]}")
print(f"elemen ke 5 bnp = {anp[4]}")

elemen ke 1 anp = 1
elemen ke 3 anp = 3
elemen ke 5 bnp = 5


In [36]:
print(f"elemen ke 1-3 anp = {anp[:3]}")
print(f"elemen ke 2-3 anp = {anp[1:3]}")
print(f"elemen ke 5 anp = {anp[4:]}")

elemen ke 1-3 anp = [1 2 3]
elemen ke 2-3 anp = [2 3]
elemen ke 5 anp = [5]


In [38]:
for i in bnp :
    print("value i =", i)

value i = 1
value i = 3
value i = 5
value i = 7
value i = 11


## Matriks

In [81]:
cnp = np.array(([1,2,3], 
                [4,5,6], 
                [7,8,9]))

dnp = np.array(([4,5,6], 
                [1,2,3], 
                [7,8,9]))

In [82]:
# perkalian matrixx menggunakan fungsi .dot
f = np.dot(cnp, dnp)
g = cnp.dot(dnp)

print(f, "\n\n", g)

[[ 27  33  39]
 [ 63  78  93]
 [ 99 123 147]] 

 [[ 27  33  39]
 [ 63  78  93]
 [ 99 123 147]]


### Tranpose

In [6]:
anp = np.array(([1,2,3], 
                [4,5,6]))
print("anp =", anp.shape)

bnp = anp.transpose()
print("bnp =", bnp.shape)

print("\n",anp)
print("\n",bnp)

anp = (2, 3)
bnp = (3, 2)

 [[1 2 3]
 [4 5 6]]

 [[1 4]
 [2 5]
 [3 6]]


### Flatten, Reshape, Resize

In [7]:
print(np.ravel(anp))
print(anp.ravel())
print(anp.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [106]:
print(anp.reshape(6,1))
print(anp)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]


In [107]:
anp.resize(6,1)
print(anp)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Stacking

In [17]:
# Hstack dan Vstack
a = np.zeros((3,3))
b = np.ones((3,3))

print(np.hstack((a, b)))
print("\n", np.vstack((a, b)))

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# concat di sini sama dengan hstack/vstack
x = np.zeros((4,4))
y = np.ones((4,4))
np.concatenate([x, y] ,axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
a = np.arange(1,4,1)
b = np.arange(4,7,1)

print((np.hstack((a, b))))
print("\n", np.vstack((a, b)))

[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]


### Advanced Array Creation

In [5]:
# dengan tipe data tertentu

a = np.array(([1,2,3], [4,5,6]), dtype = object)
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
# array dengan function

def kuadrat(baris, kolom) :
    return (baris+1) * (kolom+2)

a = np.fromfunction(kuadrat, [1,5], dtype = int)
print(a)

[[2. 3. 4. 5. 6.]]


In [126]:
def kuadrat(baris, kolom) :
    return (baris+1) * (kolom+2)

a = np.fromfunction(kuadrat, [3,5], dtype = int)
print(a)

[[ 2  3  4  5  6]
 [ 4  6  8 10 12]
 [ 6  9 12 15 18]]


In [7]:
# array dengan iterable

a = (x+x for x in range(5))

b = np.fromiter(a, dtype = int)

print(a)
print(b)

<generator object <genexpr> at 0x000001D4A0AF45F0>
[0 2 4 6 8]


In [11]:
# multi type array

tipedata = [('nama', object), ('tinggi', float)]

data = [('Roi', 175), ('Andiko', 180), ('Satroi', 170)]

a = np.array(data, dtype = tipedata)
print(a)

[('Roi', 175.) ('Andiko', 180.) ('Satroi', 170.)]


## Ordering

### Single Array

In [149]:
a = np.random.randn(1,6)
print(a)

[[-0.85951471 -1.38278781  0.82530648  1.36199829  1.26683397  0.46138042]]


In [169]:
b = np.ceil(np.random.randn(1,6)*10)
print(b)

[[  6. -15.  -8.  -3.  -6.  23.]]


In [170]:
print("nilai max =", b.max())
print("posisi max =", b.argmax())
print("nilai min =", b.min())
print("posisi min =", b.argmin())

nilai max = 23.0
posisi max = 5
nilai min = -15.0
posisi min = 1


In [175]:
print("mengurutkan b :", "\n", np.sort(b))
print("posisi terurut b :", "\n", np.argsort(b))

mengurutkan b : 
 [[-15.  -8.  -6.  -3.   6.  23.]]
posisi terurut b : 
 [[1 2 4 3 0 5]]


### Multi Array

In [178]:
c = np.ceil(np.random.randn(3,5)*10)
print(c)

[[-12.   1.  -4.  -5.   7.]
 [  9. -15.   4.  -1.  -4.]
 [-22.   9. -12.   5.   2.]]


In [179]:
print("nilai max =", c.max())
print("posisi max =", c.argmax())
print("nilai min =", c.min())
print("posisi min =", c.argmin())

nilai max = 9.0
posisi max = 5
nilai min = -22.0
posisi min = 10


In [180]:
print("mengurutkan c :", "\n", np.sort(c))
print("posisi terurut c :", "\n", np.argsort(c))

mengurutkan c : 
 [[-12.  -5.  -4.   1.   7.]
 [-15.  -4.  -1.   4.   9.]
 [-22. -12.   2.   5.   9.]]
posisi terurut c : 
 [[0 3 2 1 4]
 [1 4 3 2 0]
 [0 2 4 3 1]]


### Multi type data

In [14]:
dtipe = [('nama', 'S10'), ('tinggi', int)]
data = [('Acup', 185), ('Otong', 170), ('Yaoming', 210)]

g = np.array(data, dtype = dtipe)
print(g)

[(b'Acup', 185) (b'Otong', 170) (b'Yaoming', 210)]


In [16]:
print(np.sort(g, order = 'tinggi'))

[(b'Otong', 170) (b'Acup', 185) (b'Yaoming', 210)]
